#!/bin/sh

set -e

mkdir -p out

echo "Creating out/public..."
cp -a public out/
rm out/public/index.html
rm out/public/design.html
rm -rf out/public/javascripts/*

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME=../clojurescript
fi

CLJSC_CP='lib/*:lib/dev/*:'
for next in lib/*: src/clj: src/cljs: test/cljs:; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done

CLJSC_CP=$CLJSC_CP'src/clj:src/cljs:src/cljs-macros:test/clj:templates'

echo "Create advanced compiled JavaScript..."
java -server -cp $CLJSC_CP jline.ConsoleRunner clojure.main -e \
"(use 'start.tools)
 (build-project)"

echo "[build complete]"

