#!/bin/bash

set -e

cd `dirname $0`/..

echo "Getting lein deps..."
lein deps

cd lib

git clone https://github.com/levand/domina.git

git clone https://github.com/clojure/clojurescript.git

cd domina
git checkout -b clojurescript-one-lib c0eb06f677e0f9f72537682e3c702dd27b03e2e4

cd ../clojurescript
git checkout -b clojurescript-one-lib 329708bdd0f039241b187bc639836d9997d8fbd4
script/bootstrap

echo "Copy ClojureScript deps to lib directory..."

cp lib/compiler.jar ..
cp lib/goog.jar ..
cp lib/js.jar ..

echo "[Deps Completed]"
