#!/bin/bash

cd `dirname $0`/..

source script/setup_classpath.sh

java -server -cp $CLJSC_CP jline.ConsoleRunner clojure.main -e \
"(use 'one.sample.dev-server)
 (run-server)
 (println \"The application is being served from localhost:8080\")" --repl
