#!/bin/sh

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME=../clojurescript
fi

CLJSC_CP='lib/*:'
for next in lib/*: src/clj: src/cljs: test/cljs:; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done

CLJSC_CP=$CLJSC_CP'src/clj:src/cljs:src/cljs-macros:test/clj:templates'

java -server -cp $CLJSC_CP clojure.main -e \
"(use 'start.core)
 (run-server)
 (println \"The application is being served from localhost:8080\")
 (cljs-repl)"
