#!/bin/sh

exercises=('Back Extension'
           'Barbell Curl'
           'Bench Press'
           'Bent-over Row'
           'Chin-up'
           'Clean and Jerk'
           'Deadlift'
           'Dip'
           'Front Squat'
           'Hang Clean'
           'Overhead Squat'
           'Pull-up'
           'Push Jerk'
           'Push Press'
           'Romanian Deadlift'
           'Shoulder Press'
           'Snatch'
           'Snatch-grip Deadlift'
           'Split Jerk'
           'Squat')

[[ $# -eq 2 ]] || { echo "Usage: seed <api-key> <database-name>"; exit 0 ; }

apikey=$1
database=$2

echo "\n*** Creating 'exercises' collection"

curl -X POST https://api.mongohq.com/databases/$database/collections?_apikey=$apikey \
  -H "Content-Type: application/json" \
  -d '{"name":"exercises"}'

echo "\n*** Seeding 'exercises' collection"

for name in "${exercises[@]}"
do
  echo "\nAdding '$name' to 'exercises' collection"

  curl -X POST https://api.mongohq.com/databases/$database/collections/exercises/documents?_apikey=$apikey \
    -H "Content-Type: application/json" \
    -d "{\"document\" : {\"name\" : \"$name\"}, \"safe\" : true }"
done

